// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Follower struct {
	ID         int32         `json:"id"`
	FollowerID sql.NullInt32 `json:"follower_id"`
	FollowedID sql.NullInt32 `json:"followed_id"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type Like struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	PostID    sql.NullInt32 `json:"post_id"`
	CommentID sql.NullInt32 `json:"comment_id"`
	ReplyID   sql.NullInt32 `json:"reply_id"`
	Type      string        `json:"type"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Post struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	Likes     sql.NullInt32  `json:"likes"`
	Shares    sql.NullInt32  `json:"shares"`
	CreatedAt time.Time      `json:"created_at"`
}

type Reply struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	CommentID sql.NullInt32 `json:"comment_id"`
	Content   string        `json:"content"`
	Likes     sql.NullInt32 `json:"likes"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Active    bool           `json:"active"`
	CreatedAt sql.NullTime   `json:"created_at"`
	LastLogin sql.NullTime   `json:"last_login"`
}
